"""Item icons for the storefront grid -- Minecraft's own textures, inlined.

Every icon is a real Minecraft item/block texture, bundled at
`web/assets/icons/*.png` (sourced from PrismarineJS/minecraft-assets, a
community mirror of Minecraft's own art -- these represent items the shop's
players already own on the server, the same way any plugin or wiki shows
them). No runtime fetch: the site must render with the network off
(same rule theme.py's background pattern follows), so icons are read from
disk once, base64-encoded, and cached in memory -- one small file read at
first use, then a pure dict lookup for every request after.

`ITEM_ICON_SLUGS` maps an exact item name (as typed into `/admin` -> Add
item) to the bundled file's stem. An item with no entry -- a new item the
owner adds that this map hasn't caught up to yet -- gets no image request
either: `icon_data_uri()` returns None and the caller falls back to a plain
monogram tile (see storefront.py), never a broken `<img>` or a guessed slug.
"""
from __future__ import annotations

import base64
from functools import lru_cache
from pathlib import Path

ASSETS_DIR = Path(__file__).parent / "assets" / "icons"

# Every enchantment on the sheet is sold as an enchanted book -- Minecraft
# has one texture for that, not one per enchantment, so they all share it.
_ENCHANTED_BOOK = "enchanted_book"

ITEM_ICON_SLUGS: dict[str, str] = {
    "Aqua Affinity": _ENCHANTED_BOOK,
    "Blast Protection IV": _ENCHANTED_BOOK,
    "Depth Strider III": _ENCHANTED_BOOK,
    "Feather Falling IV": _ENCHANTED_BOOK,
    "Fire Aspect II": _ENCHANTED_BOOK,
    "Fire Protection IV": _ENCHANTED_BOOK,
    "Fortune III": _ENCHANTED_BOOK,
    "Frost Walker II": _ENCHANTED_BOOK,
    "Knockback I": _ENCHANTED_BOOK,
    "Knockback II": _ENCHANTED_BOOK,
    "Looting III": _ENCHANTED_BOOK,
    "Luck of the Sea": _ENCHANTED_BOOK,
    "Lure III": _ENCHANTED_BOOK,
    "Projectile Protection IV": _ENCHANTED_BOOK,
    "Protection IV": _ENCHANTED_BOOK,
    "Respiration III": _ENCHANTED_BOOK,
    "Sharpness V": _ENCHANTED_BOOK,
    "Silk Touch": _ENCHANTED_BOOK,
    "Smite V": _ENCHANTED_BOOK,
    "Thorns II": _ENCHANTED_BOOK,
    "Mending": _ENCHANTED_BOOK,
    "Swift Sneak": _ENCHANTED_BOOK,
    "Acacia Log": "acacia_log",
    "Birch Log": "birch_log",
    "Cherry Log": "cherry_log",
    "Crimson Stem": "crimson_stem",
    "Dark Oak Log": "dark_oak_log",
    "Jungle Log": "jungle_log",
    "Mangrove Log": "mangrove_log",
    "Oak Log": "oak_log",
    "Pale Oak Log": "pale_oak_log",
    "Spruce Log": "spruce_log",
    "Warped Stem": "warped_stem",
    "Bamboo": "bamboo",
    "Acacia Leaves": "acacia_leaves",
    "Birch Leaves": "birch_leaves",
    "Cherry Leaves": "cherry_leaves",
    "Dark Oak Leaves": "dark_oak_leaves",
    "Jungle Leaves": "jungle_leaves",
    "Mangrove Leaves": "mangrove_leaves",
    "Oak Leaves": "oak_leaves",
    "Pale Oak Leaves": "pale_oak_leaves",
    "Spruce Leaves": "spruce_leaves",
    "Acacia Sapling": "acacia_sapling",
    "Birch Sapling": "birch_sapling",
    "Cherry Sapling": "cherry_sapling",
    "Crimson Fungus": "crimson_fungus",
    "Dark Oak Sapling": "dark_oak_sapling",
    "Jungle Sapling": "jungle_sapling",
    "Mangrove Propagule": "mangrove_propagule",
    "Oak Sapling": "oak_sapling",
    "Pale Oak Sapling": "pale_oak_sapling",
    "Spruce Sapling": "spruce_sapling",
    "Warped Fungus": "warped_fungus",
    # ---- catalog expansion (potions, coloured blocks, mob drops, stone
    # adjacent, tools/armour/weapons, natural blocks, random items) ----
    'Saturation': 'potion',
    'Fire Resistance': 'potion',
    'Invisibility': 'potion',
    'Health Boost': 'potion',
    'Absorption': 'potion',
    'Haste': 'potion',
    'Health': 'potion',
    'Splash Saturation': 'splash_potion',
    'Splash Fire Resistance': 'splash_potion',
    'Splash Invisibility': 'splash_potion',
    'Splash Health Boost': 'splash_potion',
    'Splash Absorption': 'splash_potion',
    'Splash Haste': 'splash_potion',
    'Splash Health': 'splash_potion',
    'Ghost Walker': 'splash_potion',
    'White Concrete': 'white_concrete',
    'Orange Concrete': 'orange_concrete',
    'Magenta Concrete': 'magenta_concrete',
    'Light Blue Concrete': 'light_blue_concrete',
    'Yellow Concrete': 'yellow_concrete',
    'Lime Concrete': 'lime_concrete',
    'Pink Concrete': 'pink_concrete',
    'Gray Concrete': 'gray_concrete',
    'Light Gray Concrete': 'light_gray_concrete',
    'Cyan Concrete': 'cyan_concrete',
    'Purple Concrete': 'purple_concrete',
    'Blue Concrete': 'blue_concrete',
    'Brown Concrete': 'brown_concrete',
    'Green Concrete': 'green_concrete',
    'Red Concrete': 'red_concrete',
    'Black Concrete': 'black_concrete',
    'White Terracotta': 'white_terracotta',
    'Orange Terracotta': 'orange_terracotta',
    'Magenta Terracotta': 'magenta_terracotta',
    'Light Blue Terracotta': 'light_blue_terracotta',
    'Yellow Terracotta': 'yellow_terracotta',
    'Lime Terracotta': 'lime_terracotta',
    'Pink Terracotta': 'pink_terracotta',
    'Gray Terracotta': 'gray_terracotta',
    'Light Gray Terracotta': 'light_gray_terracotta',
    'Cyan Terracotta': 'cyan_terracotta',
    'Purple Terracotta': 'purple_terracotta',
    'Blue Terracotta': 'blue_terracotta',
    'Brown Terracotta': 'brown_terracotta',
    'Green Terracotta': 'green_terracotta',
    'Red Terracotta': 'red_terracotta',
    'Black Terracotta': 'black_terracotta',
    'White Glazed Terracotta': 'white_glazed_terracotta',
    'Orange Glazed Terracotta': 'orange_glazed_terracotta',
    'Magenta Glazed Terracotta': 'magenta_glazed_terracotta',
    'Light Blue Glazed Terracotta': 'light_blue_glazed_terracotta',
    'Yellow Glazed Terracotta': 'yellow_glazed_terracotta',
    'Lime Glazed Terracotta': 'lime_glazed_terracotta',
    'Pink Glazed Terracotta': 'pink_glazed_terracotta',
    'Gray Glazed Terracotta': 'gray_glazed_terracotta',
    'Light Gray Glazed Terracotta': 'light_gray_glazed_terracotta',
    'Cyan Glazed Terracotta': 'cyan_glazed_terracotta',
    'Purple Glazed Terracotta': 'purple_glazed_terracotta',
    'Blue Glazed Terracotta': 'blue_glazed_terracotta',
    'Brown Glazed Terracotta': 'brown_glazed_terracotta',
    'Green Glazed Terracotta': 'green_glazed_terracotta',
    'Red Glazed Terracotta': 'red_glazed_terracotta',
    'Black Glazed Terracotta': 'black_glazed_terracotta',
    'White Wool': 'white_wool',
    'Orange Wool': 'orange_wool',
    'Magenta Wool': 'magenta_wool',
    'Light Blue Wool': 'light_blue_wool',
    'Yellow Wool': 'yellow_wool',
    'Lime Wool': 'lime_wool',
    'Pink Wool': 'pink_wool',
    'Gray Wool': 'gray_wool',
    'Light Gray Wool': 'light_gray_wool',
    'Cyan Wool': 'cyan_wool',
    'Purple Wool': 'purple_wool',
    'Blue Wool': 'blue_wool',
    'Brown Wool': 'brown_wool',
    'Green Wool': 'green_wool',
    'Red Wool': 'red_wool',
    'Black Wool': 'black_wool',
    'White Stained Glass': 'white_stained_glass',
    'Orange Stained Glass': 'orange_stained_glass',
    'Magenta Stained Glass': 'magenta_stained_glass',
    'Light Blue Stained Glass': 'light_blue_stained_glass',
    'Yellow Stained Glass': 'yellow_stained_glass',
    'Lime Stained Glass': 'lime_stained_glass',
    'Pink Stained Glass': 'pink_stained_glass',
    'Gray Stained Glass': 'gray_stained_glass',
    'Light Gray Stained Glass': 'light_gray_stained_glass',
    'Cyan Stained Glass': 'cyan_stained_glass',
    'Purple Stained Glass': 'purple_stained_glass',
    'Blue Stained Glass': 'blue_stained_glass',
    'Brown Stained Glass': 'brown_stained_glass',
    'Green Stained Glass': 'green_stained_glass',
    'Red Stained Glass': 'red_stained_glass',
    'Black Stained Glass': 'black_stained_glass',
    'White Dye': 'white_dye',
    'Orange Dye': 'orange_dye',
    'Magenta Dye': 'magenta_dye',
    'Light Blue Dye': 'light_blue_dye',
    'Yellow Dye': 'yellow_dye',
    'Lime Dye': 'lime_dye',
    'Pink Dye': 'pink_dye',
    'Gray Dye': 'gray_dye',
    'Light Gray Dye': 'light_gray_dye',
    'Cyan Dye': 'cyan_dye',
    'Purple Dye': 'purple_dye',
    'Blue Dye': 'blue_dye',
    'Brown Dye': 'brown_dye',
    'Green Dye': 'green_dye',
    'Red Dye': 'red_dye',
    'Black Dye': 'black_dye',
    'Glass': 'glass',
    'Terracotta': 'terracotta',
    'Slimeball': 'slime_ball',
    'Gunpowder': 'gunpowder',
    'Spider Eye': 'spider_eye',
    'Bone': 'bone',
    'Leather': 'leather',
    'Rotten Flesh': 'rotten_flesh',
    'Stone': 'stone',
    'Smooth Stone': 'smooth_stone',
    'Andesite': 'andesite',
    'Diorite': 'diorite',
    'Granite': 'granite',
    'Tuff': 'tuff',
    'Dripstone Block': 'dripstone_block',
    'Cobbled Deepslate': 'cobbled_deepslate',
    'Sand': 'sand',
    'Sandstone': 'sandstone',
    'Pointed Dripstone': 'pointed_dripstone',
    'Diamond Axe': 'diamond_axe',
    'Diamond Pickaxe': 'diamond_pickaxe',
    'Diamond Shovel': 'diamond_shovel',
    'Diamond Hoe': 'diamond_hoe',
    'Diamond Helmet': 'diamond_helmet',
    'Diamond Chestplate': 'diamond_chestplate',
    'Diamond Leggings': 'diamond_leggings',
    'Diamond Boots': 'diamond_boots',
    'Netherite Helmet': 'netherite_helmet',
    'Netherite Chestplate': 'netherite_chestplate',
    'Netherite Leggings': 'netherite_leggings',
    'Netherite Boots': 'netherite_boots',
    'Diamond Sword': 'diamond_sword',
    'Diamond Sword (Fire Aspect)': 'diamond_sword',
    'Arrow': 'arrow',
    'TNT': 'tnt',
    'Moss Block': 'moss_block',
    'Pale Moss Block': 'pale_moss_block',
    'Dandelion': 'dandelion',
    'Poppy': 'poppy',
    'Blue Orchid': 'blue_orchid',
    'Allium': 'allium',
    'Azure Bluet': 'azure_bluet',
    'Red Tulip': 'red_tulip',
    'Orange Tulip': 'orange_tulip',
    'White Tulip': 'white_tulip',
    'Pink Tulip': 'pink_tulip',
    'Oxeye Daisy': 'oxeye_daisy',
    'Cornflower': 'cornflower',
    'Lily of the Valley': 'lily_of_the_valley',
    'Wither Rose': 'wither_rose',
    'Sunflower': 'sunflower',
    'Lilac': 'lilac',
    'Rose Bush': 'rose_bush',
    'Peony': 'peony',
    'Cactus': 'cactus',
    'Nether Wart': 'nether_wart',
    'Honey Block': 'honey_block',
    'Honeycomb': 'honeycomb',
    'Beehive': 'beehive',
    'Ochre Froglight': 'ochre_froglight',
    'Verdant Froglight': 'verdant_froglight',
    'Pearlescent Froglight': 'pearlescent_froglight',
}


@lru_cache(maxsize=64)
def _data_uri_for_slug(slug: str) -> str | None:
    path = ASSETS_DIR / f"{slug}.png"
    try:
        raw = path.read_bytes()
    except OSError:
        return None
    return "data:image/png;base64," + base64.b64encode(raw).decode("ascii")


def icon_data_uri(item_name: str) -> str | None:
    """The item's icon as an inline `data:` URI, or None if this item has
    no mapped icon yet -- the caller renders a monogram tile instead."""
    slug = ITEM_ICON_SLUGS.get(item_name)
    if slug is None:
        return None
    return _data_uri_for_slug(slug)
